services:
  - type: web
    name: bybit-event-mini-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7414638833:AAGLMQHQHScDJohRrIvcmYvUAcLwdV0vA5I
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000